"""fixed typos and slightly changed relationship


Revision ID: 31d5c68957ca
Revises: 81037cd859a2
Create Date: 2023-03-04 22:27:33.792024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31d5c68957ca'
down_revision = '81037cd859a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_recipe_assocation_table')
    op.add_column('recipes', sa.Column('spoonacular_id', sa.Integer(), nullable=False))
    op.drop_column('recipes', 'spoonacularId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('spoonacularId', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('recipes', 'spoonacular_id')
    op.create_table('user_recipe_assocation_table',
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('recipe_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name='user_recipe_assocation_table_recipe_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_recipe_assocation_table_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'recipe_id', name='user_recipe_assocation_table_pkey')
    )
    # ### end Alembic commands ###
