"""inital revision

Revision ID: 81037cd859a2
Revises: 
Create Date: 2023-03-04 18:55:08.169587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81037cd859a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
